homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5

group: !include groups.yaml
zone: !include zones.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml