input_select:
  fire_mode:
    name: Einsatzstatus
    options:
      - Bereitschaft
      - Alarmierung
      - Im Einsatz
    initial: Bereitschaft
    icon: mdi:fire-hydrant

automation:
##Änderung Einsatzstatus
- alias: Einsatzstatus
  trigger:
  - platform: state
    entity_id: input_select.fire_mode
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.fire_mode
        state: Alarmierung
      sequence:
      - scene: scene.alarmierung
      - service: notify.mobile_app_iphonesw
        data:
          title: FF Monheim LZ 1
          message: "!!! ALARM !!!"
    - conditions:
      - condition: state
        entity_id: input_select.fire_mode
        state: Im Einsatz
      sequence:
      - service: light.turn_off
        entity_id: all
    default: []
  mode: single

##Alarmierung
- alias: Alamierung
  trigger: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.fire_mode
      option: Alarmierung
  mode: single

##Ankunft auf Rettungswache
- alias: Ankunft Rettungswache
  trigger:
  - platform: state
    entity_id: person.sebastian_weise
    to: not_home
  condition:
  - condition: state
    entity_id: input_select.fire_mode
    state: Alarmierung
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.fire_mode
      option: Im Einsatz
  mode: single

##Ankunft Zuhause nach Einsatz
- alias: Einsatz beendet
  trigger:
  - platform: state
    entity_id: person.sebastian_weise
    to: home
  condition:
  - condition: state
    entity_id: input_select.fire_mode
    state: Im Einsatz
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.fire_mode
      option: Bereitschaft
  mode: single