config:
discovery:
hassio:
map:
webhook:
mobile_app:
history:
wake_on_lan:
zeroconf:
logbook:
recorder:
  db_url: !secret db_url
  purge_keep_days: 31

logger:
  default: info
  logs:
    homeassistant.components.tado: debug

breaking_changes:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5

sensor:
  - platform: uptime
  
  - platform: version
  
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat
      
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home
      - type: memory_free
      - type: memory_use
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2) }}'

  - platform: sql
    db_url: !secret db_url
    queries:
      - name: MariaDB size
        query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB

system_health:

input_text:
input_number:
input_datetime:
input_select:

input_boolean:
  maintenance_mode:
    name: HA restarted on demand
    icon: mdi:restart