tado:
    username: !secret tado_user
    password: !secret tado_pwd

automation:
##Abstellraum
- alias: Abstellraumfenster - Heating
  trigger:
  - platform: state
    entity_id: binary_sensor.abstellraumfenster
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.abstellraum
      hvac_mode: "{{'off' if trigger.to_state.state == 'on' else 'auto'}}"
  mode: single

##Badezimmer
- alias: Badfenster - Heating
  trigger:
  - platform: state
    entity_id: binary_sensor.badfenster
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badezimmer
      hvac_mode: "{{'off' if trigger.to_state.state == 'on' else 'auto'}}"
  mode: single

##Büro
- alias: Bürofenster open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_1
    to: 'on'
    for: '00:00:10'
  - platform: state
    entity_id: binary_sensor.burofenster_2
    to: 'on'
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: 'off'
  mode: single
- alias: Bürofenster 1 close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_1
    to: 'off'
    for: '00:00:10'
  condition:
  - condition: state
    entity_id: binary_sensor.burofenster_2
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: auto
  mode: single
- alias: Bürofenster 2 close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_2
    to: 'off'
    for: '00:00:10'
  condition:
  - condition: state
    entity_id: binary_sensor.burofenster_1
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: auto
  mode: single

##Küche
- alias: Küchentür - Heating
  trigger:
  - platform: state
    entity_id: binary_sensor.kuchentur
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kuche
      hvac_mode: "{{'off' if trigger.to_state.state == 'on' else 'auto'}}"
  mode: single

##Schlafzimmer
- alias: Schlafzimmerfenster - Heating
  trigger:
  - platform: state
    entity_id: binary_sensor.schlafzimmerfenster
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.schlafzimmer
      hvac_mode: "{{'off' if trigger.to_state.state == 'on' else 'auto'}}"
  mode: single

##Wohnzimmer
- alias: Wohnzimmertür - Heating
  trigger:
  - platform: state
    entity_id: binary_sensor.wohnzimmertur
    for: '00:00:10'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.wohnzimmer
      hvac_mode: "{{'off' if trigger.to_state.state == 'on' else 'auto'}}"
  mode: single