tado:
    username: !secret tado_user
    password: !secret tado_pwd

automation:
##Abstellraum
- alias: Abstellraumfenster open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.abstellraumfenster
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.abstellraum
      hvac_mode: 'off'
  mode: single
- alias: Abstellraumfenster close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.abstellraumfenster
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.abstellraum
      hvac_mode: auto
  mode: single

##Badezimmer
- alias: Badfenster open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.badfenster
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badezimmer
      hvac_mode: 'off'
  mode: single
- alias: Badfenster close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.badfenster
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badezimmer
      hvac_mode: auto
  mode: single

##Büro
- alias: Bürofenster open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_1
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - platform: state
    entity_id: binary_sensor.burofenster_2
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: 'off'
  mode: single
- alias: Bürofenster 1 close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_1
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.burofenster_2
    state: 'close'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: auto
  mode: single
- alias: Bürofenster 2 close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.burofenster_2
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.burofenster_1
    state: 'close'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.buro
      hvac_mode: auto
  mode: single

##Küche
- alias: Küchentür open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.kuchentur
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kuche
      hvac_mode: 'off'
  mode: single
- alias: Küchentür close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.kuchentur
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kuche
      hvac_mode: auto
  mode: single

##Schlafzimmer
- alias: Schlafzimmerfenster open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.schlafzimmerfenster
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.schlafzimmer
      hvac_mode: 'off'
  mode: single
- alias: Schlafzimmerfenster close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.schlafzimmerfenster
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.schlafzimmer
      hvac_mode: auto
  mode: single

##Wohnzimmer
- alias: Wohnzimmertür open - Heating off
  trigger:
  - platform: state
    entity_id: binary_sensor.wohnzimmertur
    to: 'open'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.wohnzimmer
      hvac_mode: 'off'
  mode: single
- alias: Wohnzimmertür close - Heating auto
  trigger:
  - platform: state
    entity_id: binary_sensor.wohnzimmertur
    to: 'close'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.wohnzimmer
      hvac_mode: auto
  mode: single